listen_addresses = '*'

shared_preload_libraries = 'pg_stat_statements'

pg_stat_statements.track = all
pg_stat_statements.max = 10000

log_statement = 'all'
log_min_duration_statement = 10

max_connections = 100
shared_buffers = 256MB
